### PR TITLE
[Feature] Net Standard

### PR DESCRIPTION
**Pull request by jonnii**

### CODE REVIEW

**Comment by jonrad** [comment]
You're a terrible person for switching test frameworks in the middle of a PR

**Comment by robertcoltheart** [comment]
I feel the pain. I've had issues getting Nunit tests to work with ReSharper and dotnet core.

**Comment by jonnii** [comment]
@robertcoltheart i'd like to get this merged, i'll hack on it to remove some of the commented out paths, can you set up the gitversion and build stuff?

**Comment by jonnii** [comment]
@robertcoltheart i copied your build stuff in and it seems to have worked...

**Pull request merged**
