### PR TITLE
Add JWT middleware for token authentication headers

### PR DESCRIPTION
**Pull request by robertcoltheart**
@jonnii What do you think about this, in principle?

Code needs some work, and I should put a bit more thought into the various extension points and customization, but I wanted to float the idea before I kick in too much effort.

This would be a new extension package, `SpeakEasy.Authenticators.Jwt`. This gives us scope to do `SpeakEasy.Serializers.Newtonsoft` and `SpeakEasy.Serializers.SystemTextJson` down the line as well.

Usage would be like this:

```c#
var settings = new HttpClientSettings();

settings.AddJwtMiddleware("https://jwt_token_url", x =>
{
    x.Authenticator = new BasicAuthenticator("user", "pass");
    x.RefreshOnExpiry = true;

    // Optionally, provide a way to parse the GET result into a raw token, in case the token is embedded in JSON etc.
    // Default is to treat GET result as JSON, and look for a well-formed JWT token
    x.TokenLocator = payload => JsonConvert.DeserializeObject<TokenContainer>(payload).Token;

    // Alternatively, treat the payload as JSON and get the token from the below JSONpath (https://goessner.net/articles/JsonPath):
    x.JsonPathToToken = "identity.token";
});

var client = HttpClient.Create("http://localhost:1337/api", settings);
```

### CODE REVIEW

**Comment by jonnii** [comment]
I think this makes sense as an add-on package. 

One thing I'd suggest is not being too opinionated on the way a token is acquired, there are a ton of different flows and it's unlikely you'll pick a set of options that are useful across the board. I think the only thing that we _must_ do is make it very easy to wire up providing the resulting jwt and have it correctly added as a bearer authorization header (the easy part). 

For example the example you're giving implies a url to generate a token but they can also be generated using RSA key pairs, this API wouldn't make sense for that. Additionally things like refresh tokens are (ime) only really useful for front ends, for back ends it's _usually_  better (and safer) to generate a _very short lived jwt_ for each request with only the scopes required to satisfy that request.

**Comment by robertcoltheart** [comment]
@jonnii Take a look and see if the refactoring I've made makes more sense. Happy to discuss further or take another pass at it, I'm not particularly wedded to this yet, although having a simple `IJwtStrategy` interface to obtain the token is probably the most flexible approach.

**Review by jonnii — APPROVED** [review]

**Comment by jonnii** [comment]
@robertcoltheart seems reasonable to me, worth trying and seeing how it feels.

**Comment by robertcoltheart** [comment]
Ok, I'll try it out with a beta release and see how we go.

**Comment by robertcoltheart** [comment]
@jonnii Need to you to take a look at the build, seems the nuget API key doesn't have permission to add new packages.

**Pull request merged**
